#########################################################
####### Uncomment to install particular software. #######
#########################################################

#########################################################
# To figure out leaf nodes and their dependencies, run:
# brew leaves | xargs brew deps --installed --for-each | sed "s/^.*:/$(tput setaf 4)&$(tput sgr0)/"
#########################################################

# Each section is arranged alphabetically.

# Taps.
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"    # Required to find alternate versions of Casks.

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew "coreutils"

# Install GNU `sed`, overwriting the built-in `sed`.
# Don’t forget to add `$(brew --prefix gnu-sed)/libexec/gnubin` to `$PATH`.
brew "gnu-sed"

# Overrides of default utilities.
brew "ack"
brew "bash"
brew "curl"
brew "grep"
brew "less" # Updated version of less.
brew "screen"
brew "telnet"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"

# Utilities.
brew "bat" # Alternative to `cat` command.
brew "bitwarden-cli" # For using Bitwarden with Raycast.
brew "diff-so-fancy" # For producing more human readable diffs.
brew "eza"
brew "fd" # Faster alternative to `find` command.
brew "fzf"
brew "git"
brew "git-extras"
brew "highlight"
brew "htop" # Alternative to `top` command.
brew "imagemagick" # For conversion of images from one format to another.
brew "mas" # Mac App Store CLI.
brew "neofetch"
brew "neovim"
brew "ripgrep" # Fast text search tool.
brew "starship" # Cross-shell prompt.
brew "uv" # Python package and project manager.
brew "yazi" # Terminal file manager.
brew "zoxide" # Smart cd replacement.

# Programming languages to be installed without version managers.
brew "lua" # For use with Vim.
brew "perl"

# Language version managers.
# We will use these to install the languages, rather than download the
# languages themselves.
brew "direnv"
brew "goenv"
brew "jenv"
brew "nodenv"
brew "pyenv"
brew "rbenv"

# Docker, Kubernetes and more.
brew "ctop" # Like `top` command, but for Docker.
brew "dive" # Inspect Docker images in depth.
brew "helm"
brew "kubernetes-cli"
brew "kubectx"
brew "k9s"
brew "lazydocker"
brew "stern"

# Formatting, linting, code quality and analysis tools.
brew "clang-format"
brew "google-java-format"
brew "pre-commit"
brew "rust-analyzer"
brew "shfmt"

# Other programming related packages.
brew "kcat"
brew "redis"
brew "stdman"

# Miscellaneous.
# brew "khanhas/tap/spicetify-cli" # For customising the look of Spotify.

# GUI applications.
cask "adguard"
cask "appcleaner"
cask "arc"
cask "cloudflare-warp" # Best general purpose VPN.
cask "daisydisk"
# cask "deepl"
cask "downie"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "iina" # Much better native alternative to VLC.
cask "imageoptim"
cask "istat-menus"
cask "itsycal" # Utility for displaying calendar events in the menu bar.
cask "kap"
cask "maccy" # Clipboard manager.
cask "macmediakeyforwarder"
cask "notunes" # Prevent iTunes or Apple Music from launching.
cask "rectangle" # Alternative to Spectacle as it is no longer maintained.
cask "spotify"
cask "transmission"

# Quick-look plugins.
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "syntax-highlight"
cask "suspicious-package"
cask "webpquicklook"

# Languages and SDKs.
cask "flutter"
cask "temurin17"

# Development utilities.
# cask "android-studio"
# cask "datagrip"
cask "docker"
# cask "google-cloud-sdk"
# cask "intellij-idea"
cask "iterm2"
cask "mongodb-compass"
cask "postman"
cask "raycast" # Alternative to Spotlight and Alfred with focus on development features.
cask "redisinsight"
cask "visual-studio-code"

# Fonts.
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font" # Our terminal font.

# Mac App Store apps.
mas "Amphetamine", id: 937984704
mas "Balance Lock", id: 1019371109 # Fix Mac bug which causes sound balance to shift when using bluetooth headphones.
mas "Bitwarden", id: 1352778147
mas "OneDrive", id: 823766827
mas "PiPifier", id: 1160374471
mas "Speedtest", id: 1153157709
mas "Super Agent", id: 1568262835 # Automatically deals with cookie consent on Safari.
mas "The Unarchiver", id: 425424353
