#########################################################
####### Uncomment to install particular software. #######
#########################################################

# Taps.
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"    # Required to find alternate versions of Casks.
tap "mongodb/brew"

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew "coreutils"

# Install GNU `sed`, overwriting the built-in `sed`.
# Don’t forget to add `$(brew --prefix gnu-sed)/libexec/gnubin` to `$PATH`.
brew "gnu-sed"

# Utilities.
brew "bitwarden-cli" # For using Bitwarden with Raycast.
brew "diff-so-fancy" # For producing more human readable diffs.
brew "fzf"
brew "less" # Updated version of less.
brew "watchman"
brew "wget"
brew "tmux"
brew "vim"
brew "neovim"
brew "grep"
brew "htop"
brew "screen"
brew "direnv"
brew "highlight"
brew "imagemagick" # For conversion of images from one format to another.
brew "jenv"
brew "kubernetes-cli"
brew "kubectx"
brew "k9s"
brew "helm"
brew "telnet"
brew "ranger"
brew "stern"

# Faster and easier finding.
brew "fd" # Faster alternative to `find` command.
brew "the_silver_searcher" # Provides the `ag` command.

# Programming related packages.
# brew "clang-format"
brew "cmake"
# brew "composer"
brew "go"
brew "google-java-format"
# brew "facebook/fb/idb-companion" # To automate iOS simulators and devices for development.
brew "lua"
brew "mongodb-community@4.2" # The latest version at the time (4.4) has some issue with trying to connect.
brew "perl"
brew "php" # Since macos no longer ships with php.
brew "postgresql"
brew "python"
brew "redis"
brew "ruby"
brew "rust-analyzer"
brew "shfmt"
brew "sqlite"
brew "stdman"
brew "yarn"

# Install other useful binaries.
brew "ack"
# brew "awscli"
brew "bash"
brew "bat"
brew "curl"
brew "git"
brew "khanhas/tap/spicetify-cli" # For customising the look of Spotify.
brew "neofetch"
brew "tree"

# GUI applications.
cask "adguard"
cask "appcleaner"
cask "arc"
cask "cloudflare-warp" # Best general purpose VPN.
cask "daisydisk"
# cask "deepl"
cask "downie"
cask "dropbox"
cask "firefox"
cask "firefox-developer-edition"
cask "google-chrome"
cask "iina" # Much better native alternative to VLC.
cask "imageoptim"
cask "istat-menus"
cask "itsycal" # Utility for displaying calendar events in the menu bar.
cask "kap"
cask "logitech-options"
cask "maccy" # Clipboard manager.
cask "macmediakeyforwarder"
cask "notunes" # Prevent iTunes or Apple Music from launching.
cask "rectangle" # Alternative to Spectacle as it is no longer maintained.
cask "spotify"
cask "transmission"

# Quick-look plugins.
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "syntax-highlight"
cask "suspicious-package"
cask "webpquicklook"

# Languages and SDKs.
cask "flutter"
cask "temurin8"
cask "temurin11"
cask "temurin17"

# Development utilities.
# cask "android-studio"
cask "datagrip"
cask "drawio"
# cask "google-cloud-sdk"
cask "intellij-idea"
cask "iterm2"
cask "mongodb-compass"
cask "postman"
cask "raycast" # Alternative to Spotlight and Alfred with focus on development features.
cask "redisinsight"
cask "visual-studio-code"

# Fonts.
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font" # Our terminal font.

# Mac App Store apps.
mas "Amphetamine", id: 937984704
mas "Balance Lock", id: 1019371109 # Fix Mac bug which causes sound balance to shift when using bluetooth headphones.
mas "Bitwarden", id: 1352778147
mas "PiPifier", id: 1160374471
mas "Super Agent", id: 1568262835 # Automatically deals with cookie consent on Safari.
mas "The Unarchiver", id: 425424353
mas "Speedtest", id: 1153157709
