# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json

gui:
  # Catppuccin Macchiato Theme
  theme:
    activeBorderColor:
      - "#f5a97f" # peach
      - bold
    inactiveBorderColor:
      - "#6e738d" # overlay0
    selectedLineBgColor:
      - "#363a4f" # surface0
    optionsTextColor:
      - "#f5a97f" # peach
