# yaml-language-server: $schema=https://raw.githubusercontent.com/derailed/k9s/master/internal/config/json/schemas/k9s.json

k9s:
  liveViewAutoRefresh: true
  ui:
    enableMouse: true
    logoless: true
    skin: catppuccin-macchiato
  logger:
    textWrap: true
    disableAutoscroll: true
