gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  sidePanelWidth: 0.25
  scrollHeight: 30 # Default is too less

  # Catppuccin Macchiato Theme
  # To switch accents: comment out the current active accent and uncomment your preferred one
  # ===== GREEN =====
  # theme:
  #   activeBorderColor:
  #     - "#a6da95"
  #     - bold
  #   inactiveBorderColor:
  #     - "#a5adcb"
  #   optionsTextColor:
  #     - "#8aadf4"
  #   selectedLineBgColor:
  #     - "#363a4f"
  #   cherryPickedCommitBgColor:
  #     - "#494d64"
  #   cherryPickedCommitFgColor:
  #     - "#a6da95"
  #   unstagedChangesColor:
  #     - "#ed8796"
  #   defaultFgColor:
  #     - "#cad3f5"
  #   searchingActiveBorderColor:
  #     - "#eed49f"
  #
  # authorColors:
  #   "*": "#b7bdf8"

  # ===== MAROON =====
  # theme:
  #   activeBorderColor:
  #     - "#ee99a0"
  #     - bold
  #   inactiveBorderColor:
  #     - "#a5adcb"
  #   optionsTextColor:
  #     - "#8aadf4"
  #   selectedLineBgColor:
  #     - "#363a4f"
  #   cherryPickedCommitBgColor:
  #     - "#494d64"
  #   cherryPickedCommitFgColor:
  #     - "#ee99a0"
  #   unstagedChangesColor:
  #     - "#ed8796"
  #   defaultFgColor:
  #     - "#cad3f5"
  #   searchingActiveBorderColor:
  #     - "#eed49f"
  #
  # authorColors:
  #   "*": "#b7bdf8"

  # ===== PEACH =====
  theme:
    activeBorderColor:
      - "#f5a97f"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#f5a97f"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"

  authorColors:
    "*": "#b7bdf8"

git:
  # Better diff context
  diffContextSize: 4

  paging:
    colorArg: always
    # Set lazygit specific options for delta.
    # If you want to customize the delta options for lazygit, you can do so here.
    # For example, if you want to hide the file headers and hunk headers,
    # you can use the following options:
    #
    #   pager: delta --paging=never --hunk-header-style=omit --file-header-style=omit
    pager: delta --paging=never
