# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Place your regular format here
# format = """$directory$all$fill$time
# $character
# """
# format = """$directory$fill$time
# $all
# $character"""

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$fill\
$time\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$netns\
$shell\
$character"""

command_timeout = 1000 # Increase the timeout as there are some commands that exceed the default 500ms budget at times.

[directory]
# Show full path (or N last directories)
fish_style_pwd_dir_length = 2
truncation_length = 3               # Show last 3 directories
truncate_to_repo = false            # Don't stop truncating at repo root
read_only = " "                    # Optional: shows icon if dir is read-only
read_only_style = "red"

[kubernetes]
disabled = false
style = "bright-blue bold"

[fill]
symbol = "·"

[time]
disabled = false
format = "[\uf017 $time]($style)"
time_format = "%H:%M:%S"
